// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
//using Google.Maps;
using UIKit;
using Mapbox;
using CoreLocation;

namespace Lasallistas.iOS
{
	public partial class MapViewController : UIViewController
	{

        //MapView _mapView;
		public MapViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var url = new NSUrl("mapbox://styles/mapbox/streets-v10");

            var mapViewView = new MGLMapView(View.Bounds,url);
            //mapViewView.StyleURL = MGLStyle.DarkStyleURL;
            mapViewView.AutoresizingMask = UIViewAutoresizing.FlexibleDimensions;
            mapViewView.SetCenterCoordinate(new CLLocationCoordinate2D(21.152212, -101.711294), 9, false);
            View.AddSubview(mapViewView);
            mapView.Hidden = true;
            
        }
    }
}
