// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Lasallistas.iOS
{
	public partial class CalendarioPartidoTableCell : UITableViewCell
	{
		public CalendarioPartidoTableCell (IntPtr handle) : base (handle)
		{
		}
	}
}
